### PR TITLE
Minor UI improvements

### PR DESCRIPTION
**Pull request by cjbrooks12**
Adds title attributes to icons, and "Enabled/Disabled" text to Target buttons for clarity.

### CODE REVIEW

**Comment by terrakok** [comment]
I'm ready to approve part with the top menu titles. But I don't like texts under target buttons. To understand how they work one click is enough, I think

**Comment by cjbrooks12** [comment]
I really think the target buttons need something other than color to indicate whether they're selected or not. If you have to click a button to understand what it does, that's a problem in terms of usability. And personally, I was still unsure of whether colored meant selected or unselected even after clicking on it; it wasn't until I actually downloaded the project that I knew for sure which targets were selected.

How would you feel if I were to try some other patterns to emphasize whether a button is selected or not? For example, like shown in [this article](https://uxmovement.com/buttons/why-toggle-buttons-are-confusing/).

image

**Comment by terrakok** [comment]
Yes, let's try that one

**Comment by terrakok** [comment]
image

**Pull request closed without merging**
