### PR TITLE
Add support for Kermit

### PR DESCRIPTION
**Pull request by findjigar**
Added support for `Kermit` logging library for Kotlin Multiplatform

#### Testing
`./gradlew check` - passed locally

### CODE REVIEW

**Comment by terrakok** [comment]
I don't think it is a good idea to have equal libraries in the list.

**Comment by terrakok** [comment]
I have an idea to make some cards configurable. For example, a card for selection a log engine

**Comment by findjigar** [comment]
@terrakok I followed the idea from here where both Kermit and Napier are there
Screen Shot 2023-04-06 at 12 51 49 PM

https://terrakok.github.io/kmp-web-wizard/

**Comment by terrakok** [comment]
I made a dialog for selecting the library to use.

image
image

**Pull request closed without merging**
